FROM golang:1.24-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-s -w" -o /out/network-edr-server ./server

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/network-edr-server /network-edr-server
EXPOSE 8080
USER nonroot:nonroot
ENTRYPOINT ["/network-edr-server"]
