FROM golang:1.24-alpine AS build
RUN apk add --no-cache libpcap-dev gcc musl-dev
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-s -w" -o /out/network-edr-agent ./agent

FROM alpine:3.22
RUN apk add --no-cache libpcap
COPY --from=build /out/network-edr-agent /network-edr-agent
ENTRYPOINT ["/network-edr-agent"]
